// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Campaign struct {
	ID               pgtype.UUID        `json:"id"`
	ChainCampaignID  pgtype.Int8        `json:"chain_campaign_id"`
	OwnerAddress     string             `json:"owner_address"`
	Title            string             `json:"title"`
	ShortDescription string             `json:"short_description"`
	LongDescription  string             `json:"long_description"`
	Category         string             `json:"category"`
	TargetAmount     pgtype.Numeric     `json:"target_amount"`
	CoverImageUrl    string             `json:"cover_image_url"`
	BeneficiaryName  string             `json:"beneficiary_name"`
	Location         string             `json:"location"`
	ExpectedImpact   string             `json:"expected_impact"`
	MetadataUri      pgtype.Text        `json:"metadata_uri"`
	CreateTxHash     pgtype.Text        `json:"create_tx_hash"`
	LatestTrustScore pgtype.Int4        `json:"latest_trust_score"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Certificate struct {
	ID               pgtype.UUID        `json:"id"`
	CampaignID       pgtype.UUID        `json:"campaign_id"`
	DonationID       pgtype.UUID        `json:"donation_id"`
	ProofID          pgtype.UUID        `json:"proof_id"`
	RecipientAddress string             `json:"recipient_address"`
	CertificateType  string             `json:"certificate_type"`
	CertificateUri   pgtype.Text        `json:"certificate_uri"`
	CertificateHash  string             `json:"certificate_hash"`
	IssueTxHash      pgtype.Text        `json:"issue_tx_hash"`
	Status           string             `json:"status"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
}

type Donation struct {
	ID            pgtype.UUID        `json:"id"`
	CampaignID    pgtype.UUID        `json:"campaign_id"`
	DonorAddress  string             `json:"donor_address"`
	Amount        pgtype.Numeric     `json:"amount"`
	TxHash        string             `json:"tx_hash"`
	CertificateID pgtype.UUID        `json:"certificate_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Proof struct {
	ID                      pgtype.UUID        `json:"id"`
	CampaignID              pgtype.UUID        `json:"campaign_id"`
	Title                   string             `json:"title"`
	Description             string             `json:"description"`
	AmountUsed              pgtype.Numeric     `json:"amount_used"`
	ImpactClaim             string             `json:"impact_claim"`
	FileUrl                 string             `json:"file_url"`
	FileHash                string             `json:"file_hash"`
	ProofUri                pgtype.Text        `json:"proof_uri"`
	SubmitTxHash            pgtype.Text        `json:"submit_tx_hash"`
	AiStatus                string             `json:"ai_status"`
	AiSummary               pgtype.Text        `json:"ai_summary"`
	AiDetectedItems         []byte             `json:"ai_detected_items"`
	AiConsistency           pgtype.Text        `json:"ai_consistency"`
	AiRisk                  pgtype.Text        `json:"ai_risk"`
	AiEstimatedImpact       pgtype.Text        `json:"ai_estimated_impact"`
	AiTrustScore            pgtype.Int4        `json:"ai_trust_score"`
	AiCertificateImpactText pgtype.Text        `json:"ai_certificate_impact_text"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}
