// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
  owner_address, title, short_description, long_description, category, target_amount, cover_image_url, beneficiary_name, location, expected_impact
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, chain_campaign_id, owner_address, title, short_description, long_description, category, target_amount, cover_image_url, beneficiary_name, location, expected_impact, metadata_uri, create_tx_hash, latest_trust_score, created_at, updated_at
`

type CreateCampaignParams struct {
	OwnerAddress     string         `json:"owner_address"`
	Title            string         `json:"title"`
	ShortDescription string         `json:"short_description"`
	LongDescription  string         `json:"long_description"`
	Category         string         `json:"category"`
	TargetAmount     pgtype.Numeric `json:"target_amount"`
	CoverImageUrl    string         `json:"cover_image_url"`
	BeneficiaryName  string         `json:"beneficiary_name"`
	Location         string         `json:"location"`
	ExpectedImpact   string         `json:"expected_impact"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.OwnerAddress,
		arg.Title,
		arg.ShortDescription,
		arg.LongDescription,
		arg.Category,
		arg.TargetAmount,
		arg.CoverImageUrl,
		arg.BeneficiaryName,
		arg.Location,
		arg.ExpectedImpact,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ChainCampaignID,
		&i.OwnerAddress,
		&i.Title,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Category,
		&i.TargetAmount,
		&i.CoverImageUrl,
		&i.BeneficiaryName,
		&i.Location,
		&i.ExpectedImpact,
		&i.MetadataUri,
		&i.CreateTxHash,
		&i.LatestTrustScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificates (
  campaign_id, donation_id, proof_id, recipient_address, certificate_type, certificate_hash
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, campaign_id, donation_id, proof_id, recipient_address, certificate_type, certificate_uri, certificate_hash, issue_tx_hash, status, issued_at
`

type CreateCertificateParams struct {
	CampaignID       pgtype.UUID `json:"campaign_id"`
	DonationID       pgtype.UUID `json:"donation_id"`
	ProofID          pgtype.UUID `json:"proof_id"`
	RecipientAddress string      `json:"recipient_address"`
	CertificateType  string      `json:"certificate_type"`
	CertificateHash  string      `json:"certificate_hash"`
}

func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		arg.CampaignID,
		arg.DonationID,
		arg.ProofID,
		arg.RecipientAddress,
		arg.CertificateType,
		arg.CertificateHash,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DonationID,
		&i.ProofID,
		&i.RecipientAddress,
		&i.CertificateType,
		&i.CertificateUri,
		&i.CertificateHash,
		&i.IssueTxHash,
		&i.Status,
		&i.IssuedAt,
	)
	return i, err
}

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (
  campaign_id, donor_address, amount, tx_hash
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, campaign_id, donor_address, amount, tx_hash, certificate_id, created_at
`

type CreateDonationParams struct {
	CampaignID   pgtype.UUID    `json:"campaign_id"`
	DonorAddress string         `json:"donor_address"`
	Amount       pgtype.Numeric `json:"amount"`
	TxHash       string         `json:"tx_hash"`
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createDonation,
		arg.CampaignID,
		arg.DonorAddress,
		arg.Amount,
		arg.TxHash,
	)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DonorAddress,
		&i.Amount,
		&i.TxHash,
		&i.CertificateID,
		&i.CreatedAt,
	)
	return i, err
}

const createProof = `-- name: CreateProof :one
INSERT INTO proofs (
  campaign_id, title, description, amount_used, impact_claim, file_url, file_hash
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, campaign_id, title, description, amount_used, impact_claim, file_url, file_hash, proof_uri, submit_tx_hash, ai_status, ai_summary, ai_detected_items, ai_consistency, ai_risk, ai_estimated_impact, ai_trust_score, ai_certificate_impact_text, created_at
`

type CreateProofParams struct {
	CampaignID  pgtype.UUID    `json:"campaign_id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AmountUsed  pgtype.Numeric `json:"amount_used"`
	ImpactClaim string         `json:"impact_claim"`
	FileUrl     string         `json:"file_url"`
	FileHash    string         `json:"file_hash"`
}

func (q *Queries) CreateProof(ctx context.Context, arg CreateProofParams) (Proof, error) {
	row := q.db.QueryRow(ctx, createProof,
		arg.CampaignID,
		arg.Title,
		arg.Description,
		arg.AmountUsed,
		arg.ImpactClaim,
		arg.FileUrl,
		arg.FileHash,
	)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.AmountUsed,
		&i.ImpactClaim,
		&i.FileUrl,
		&i.FileHash,
		&i.ProofUri,
		&i.SubmitTxHash,
		&i.AiStatus,
		&i.AiSummary,
		&i.AiDetectedItems,
		&i.AiConsistency,
		&i.AiRisk,
		&i.AiEstimatedImpact,
		&i.AiTrustScore,
		&i.AiCertificateImpactText,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, chain_campaign_id, owner_address, title, short_description, long_description, category, target_amount, cover_image_url, beneficiary_name, location, expected_impact, metadata_uri, create_tx_hash, latest_trust_score, created_at, updated_at FROM campaigns
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.ChainCampaignID,
		&i.OwnerAddress,
		&i.Title,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Category,
		&i.TargetAmount,
		&i.CoverImageUrl,
		&i.BeneficiaryName,
		&i.Location,
		&i.ExpectedImpact,
		&i.MetadataUri,
		&i.CreateTxHash,
		&i.LatestTrustScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, campaign_id, donation_id, proof_id, recipient_address, certificate_type, certificate_uri, certificate_hash, issue_tx_hash, status, issued_at FROM certificates
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCertificate(ctx context.Context, id pgtype.UUID) (Certificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, id)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DonationID,
		&i.ProofID,
		&i.RecipientAddress,
		&i.CertificateType,
		&i.CertificateUri,
		&i.CertificateHash,
		&i.IssueTxHash,
		&i.Status,
		&i.IssuedAt,
	)
	return i, err
}

const getDonation = `-- name: GetDonation :one
SELECT id, campaign_id, donor_address, amount, tx_hash, certificate_id, created_at FROM donations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDonation(ctx context.Context, id pgtype.UUID) (Donation, error) {
	row := q.db.QueryRow(ctx, getDonation, id)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DonorAddress,
		&i.Amount,
		&i.TxHash,
		&i.CertificateID,
		&i.CreatedAt,
	)
	return i, err
}

const getDonationByTxHash = `-- name: GetDonationByTxHash :one
SELECT id, campaign_id, donor_address, amount, tx_hash, certificate_id, created_at FROM donations
WHERE tx_hash = $1 LIMIT 1
`

func (q *Queries) GetDonationByTxHash(ctx context.Context, txHash string) (Donation, error) {
	row := q.db.QueryRow(ctx, getDonationByTxHash, txHash)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DonorAddress,
		&i.Amount,
		&i.TxHash,
		&i.CertificateID,
		&i.CreatedAt,
	)
	return i, err
}

const getDonationsByCampaign = `-- name: GetDonationsByCampaign :many
SELECT id, campaign_id, donor_address, amount, tx_hash, certificate_id, created_at FROM donations
WHERE campaign_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDonationsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Donation, error) {
	rows, err := q.db.Query(ctx, getDonationsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.DonorAddress,
			&i.Amount,
			&i.TxHash,
			&i.CertificateID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProof = `-- name: GetProof :one
SELECT id, campaign_id, title, description, amount_used, impact_claim, file_url, file_hash, proof_uri, submit_tx_hash, ai_status, ai_summary, ai_detected_items, ai_consistency, ai_risk, ai_estimated_impact, ai_trust_score, ai_certificate_impact_text, created_at FROM proofs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProof(ctx context.Context, id pgtype.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, getProof, id)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Title,
		&i.Description,
		&i.AmountUsed,
		&i.ImpactClaim,
		&i.FileUrl,
		&i.FileHash,
		&i.ProofUri,
		&i.SubmitTxHash,
		&i.AiStatus,
		&i.AiSummary,
		&i.AiDetectedItems,
		&i.AiConsistency,
		&i.AiRisk,
		&i.AiEstimatedImpact,
		&i.AiTrustScore,
		&i.AiCertificateImpactText,
		&i.CreatedAt,
	)
	return i, err
}

const linkDonationCertificate = `-- name: LinkDonationCertificate :exec
UPDATE donations
SET certificate_id = $2
WHERE id = $1
`

type LinkDonationCertificateParams struct {
	ID            pgtype.UUID `json:"id"`
	CertificateID pgtype.UUID `json:"certificate_id"`
}

func (q *Queries) LinkDonationCertificate(ctx context.Context, arg LinkDonationCertificateParams) error {
	_, err := q.db.Exec(ctx, linkDonationCertificate, arg.ID, arg.CertificateID)
	return err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, chain_campaign_id, owner_address, title, short_description, long_description, category, target_amount, cover_image_url, beneficiary_name, location, expected_impact, metadata_uri, create_tx_hash, latest_trust_score, created_at, updated_at FROM campaigns
ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.ChainCampaignID,
			&i.OwnerAddress,
			&i.Title,
			&i.ShortDescription,
			&i.LongDescription,
			&i.Category,
			&i.TargetAmount,
			&i.CoverImageUrl,
			&i.BeneficiaryName,
			&i.Location,
			&i.ExpectedImpact,
			&i.MetadataUri,
			&i.CreateTxHash,
			&i.LatestTrustScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificateTxHash = `-- name: UpdateCertificateTxHash :exec
UPDATE certificates
SET issue_tx_hash = $2, status = 'issued', issued_at = NOW()
WHERE id = $1
`

type UpdateCertificateTxHashParams struct {
	ID          pgtype.UUID `json:"id"`
	IssueTxHash pgtype.Text `json:"issue_tx_hash"`
}

func (q *Queries) UpdateCertificateTxHash(ctx context.Context, arg UpdateCertificateTxHashParams) error {
	_, err := q.db.Exec(ctx, updateCertificateTxHash, arg.ID, arg.IssueTxHash)
	return err
}

const updateProofAIAssessment = `-- name: UpdateProofAIAssessment :exec
UPDATE proofs
SET ai_status = $2, ai_summary = $3, ai_detected_items = $4, ai_consistency = $5, ai_risk = $6, ai_estimated_impact = $7, ai_trust_score = $8
WHERE id = $1
`

type UpdateProofAIAssessmentParams struct {
	ID                pgtype.UUID `json:"id"`
	AiStatus          string      `json:"ai_status"`
	AiSummary         pgtype.Text `json:"ai_summary"`
	AiDetectedItems   []byte      `json:"ai_detected_items"`
	AiConsistency     pgtype.Text `json:"ai_consistency"`
	AiRisk            pgtype.Text `json:"ai_risk"`
	AiEstimatedImpact pgtype.Text `json:"ai_estimated_impact"`
	AiTrustScore      pgtype.Int4 `json:"ai_trust_score"`
}

func (q *Queries) UpdateProofAIAssessment(ctx context.Context, arg UpdateProofAIAssessmentParams) error {
	_, err := q.db.Exec(ctx, updateProofAIAssessment,
		arg.ID,
		arg.AiStatus,
		arg.AiSummary,
		arg.AiDetectedItems,
		arg.AiConsistency,
		arg.AiRisk,
		arg.AiEstimatedImpact,
		arg.AiTrustScore,
	)
	return err
}

const updateProofTxHash = `-- name: UpdateProofTxHash :exec
UPDATE proofs
SET submit_tx_hash = $2
WHERE id = $1
`

type UpdateProofTxHashParams struct {
	ID           pgtype.UUID `json:"id"`
	SubmitTxHash pgtype.Text `json:"submit_tx_hash"`
}

func (q *Queries) UpdateProofTxHash(ctx context.Context, arg UpdateProofTxHashParams) error {
	_, err := q.db.Exec(ctx, updateProofTxHash, arg.ID, arg.SubmitTxHash)
	return err
}
