// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error)
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateProof(ctx context.Context, arg CreateProofParams) (Proof, error)
	GetCampaign(ctx context.Context, id pgtype.UUID) (Campaign, error)
	GetCertificate(ctx context.Context, id pgtype.UUID) (Certificate, error)
	GetDonation(ctx context.Context, id pgtype.UUID) (Donation, error)
	GetDonationByTxHash(ctx context.Context, txHash string) (Donation, error)
	GetDonationsByCampaign(ctx context.Context, campaignID pgtype.UUID) ([]Donation, error)
	GetProof(ctx context.Context, id pgtype.UUID) (Proof, error)
	LinkDonationCertificate(ctx context.Context, arg LinkDonationCertificateParams) error
	ListCampaigns(ctx context.Context) ([]Campaign, error)
	UpdateCertificateTxHash(ctx context.Context, arg UpdateCertificateTxHashParams) error
	UpdateProofAIAssessment(ctx context.Context, arg UpdateProofAIAssessmentParams) error
	UpdateProofTxHash(ctx context.Context, arg UpdateProofTxHashParams) error
}

var _ Querier = (*Queries)(nil)
