version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: aidnara_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pnj123
      POSTGRES_DB: aidnara
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
